services:
  user-db:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=user
        - POSTGRES_USER=user
        - POSTGRES_DB=user
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
